import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  let words, speed, current, interval;
  words = ['']
  current = 0

  const clickHandler = function (event) {
    start(event);
    stop(event);
  };

  const start = function (event) {

    if (event.target.id !== 'start' || !text.value.length) return;

    words = text.value.split(' ').filter(function (word) {
      return word.length;
    });


    speed = (60 / parseInt(wpm.value, 10)) * 1000;

    current = 0;

    run();

  };

  const run = function () {

    // Run the reader
    interval = setInterval(function () {

      // If there are no more words, stop
      if (!words[current]) {
        end();
        return;
      }

      current++;

    }, speed);

  };

  const stop = function (event) {

    if (event.target.id !== 'stop') return;

    end();

  };

  var end = function () {
    clearInterval(interval);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <details id="settings">
          <summary>Settings</summary>

          <label htmlFor="text">Text to Read</label>
          <textarea id="text"></textarea>

          <label htmlFor="wpm">Words Per Minute</label>
          <input type="tel" id="wpm" min="1" value="250" />

          <button onClick={clickHandler} id="start">Start</button> <button id="stop">Stop</button>
        </details>
        <div id={styles.readerWrapper}>
          <div id="reader" aria-live="assertive">
            {

            }

          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
